[package]
org = "sachinira"
name = "template_sfdc_marketing_campaign_emails_to_csv"
version = "0.1.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "sfdc"
version = "2.1.6"
